/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_itrunner_ndk_test3_MainActivity */

#ifndef _Included_cn_itrunner_ndk_test3_MainActivity
#define _Included_cn_itrunner_ndk_test3_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_itrunner_ndk_test3_MainActivity
 * Method:    getData
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_itrunner_ndk_1test3_MainActivity_getData
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
